### PR TITLE
Nginx 1.7.10

### PR DESCRIPTION
**Pull request by TheDude05**
Update to Nginx 1.7.10. Also add the "txid" module which allows generation of unique tokens for every request

### CODE REVIEW

**Comment by dermusikman** [comment]
Running `make`, I fail here:
```
configuring additional modules
adding module in /root/rpmbuild/SOURCES/ngx_txid
./configure: error: no /root/rpmbuild/SOURCES/ngx_txid/config was found
error: Bad exit status from /var/tmp/rpm-tmp.iRyo6w (%build)


RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.iRyo6w (%build)
make: *** [centos6] Error 1
```

**Comment by dermusikman** [comment]
RPM has a broken dependency:
```
[spieler@test-ruby-rpm ~]$ sudo yum localinstall nginx-1.7.10-1.el6_intox.x86_64.rpm
Loaded plugins: downloadonly, fastestmirror, security
Setting up Local Package Process
Examining nginx-1.7.10-1.el6_intox.x86_64.rpm: nginx-1.7.10-1.el6_intox.x86_64
Marking nginx-1.7.10-1.el6_intox.x86_64.rpm to be installed
Loading mirror speeds from cached hostfile
 * base: mirrors.gigenet.com
 * extras: mirror.rackspace.com
 * updates: mirror.rackspace.com
Resolving Dependencies
--> Running transaction check
---> Package nginx.x86_64 0:1.7.10-1.el6_intox will be installed
--> Processing Dependency: GeoIP for package: nginx-1.7.10-1.el6_intox.x86_64
--> Processing Dependency: gd for package: nginx-1.7.10-1.el6_intox.x86_64
--> Processing Dependency: libxslt.so.1(LIBXML2_1.0.11)(64bit) for package: nginx-1.7.10-1.el6_intox.x86_64
--> Processing Dependency: libxslt.so.1(LIBXML2_1.0.18)(64bit) for package: nginx-1.7.10-1.el6_intox.x86_64
--> Processing Dependency: libGeoIP.so.1()(64bit) for package: nginx-1.7.10-1.el6_intox.x86_64
--> Processing Dependency: libexslt.so.0()(64bit) for package: nginx-1.7.10-1.el6_intox.x86_64
--> Processing Dependency: libgd.so.2()(64bit) for package: nginx-1.7.10-1.el6_intox.x86_64
--> Processing Dependency: libxslt.so.1()(64bit) for package: nginx-1.7.10-1.el6_intox.x86_64
--> Running transaction check
---> Package gd.x86_64 0:2.0.35-11.el6 will be installed
--> Processing Dependency: libXpm.so.4()(64bit) for package: gd-2.0.35-11.el6.x86_64
---> Package libxslt.x86_64 0:1.1.26-2.el6_3.1 will be installed
---> Package nginx.x86_64 0:1.7.10-1.el6_intox will be installed
--> Processing Dependency: GeoIP for package: nginx-1.7.10-1.el6_intox.x86_64
--> Processing Dependency: libGeoIP.so.1()(64bit) for package: nginx-1.7.10-1.el6_intox.x86_64
--> Running transaction check
---> Package libXpm.x86_64 0:3.5.10-2.el6 will be installed
---> Package nginx.x86_64 0:1.7.10-1.el6_intox will be installed
--> Processing Dependency: GeoIP for package: nginx-1.7.10-1.el6_intox.x86_64
--> Processing Dependency: libGeoIP.so.1()(64bit) for package: nginx-1.7.10-1.el6_intox.x86_64
--> Finished Dependency Resolution
Error: Package: nginx-1.7.10-1.el6_intox.x86_64 (/nginx-1.7.10-1.el6_intox.x86_64)
           Requires: libGeoIP.so.1()(64bit)
Error: Package: nginx-1.7.10-1.el6_intox.x86_64 (/nginx-1.7.10-1.el6_intox.x86_64)
           Requires: GeoIP
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest
```

**Comment by TheDude05** [comment]
Yea thats unfortunately a known issue which I believe is not a problem on EL7 systems. See ID-276

**Comment by dermusikman** [comment]
Got it. Installed EPEL and it's good, so LGTM

**Pull request merged**
